# -*- coding: utf-8 -*-
"""Bank-note-Authentication.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H1hJBJh9TRK1H5GR5Y0PuwScgTtUxBsd
"""

import numpy as np
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/Dataset/Bank note Authentication/BankNoteAuthentication.csv')

data.head()

data.info()

data.describe(include = 'all')

data.isnull().sum()

import seaborn as sns

corr = data.corr()
sns.heatmap(corr, annot = True, cmap = 'coolwarm')

sns.pairplot(data)

data.columns

X = data[['variance', 'skewness', 'curtosis', 'entropy']]
y = data['class']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=2529)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

X_train = ss.fit_transform(X_train)
X_test = ss.fit_transform(X_test)

from sklearn.linear_model import  LogisticRegression

lr = LogisticRegression()
lr.fit(X_train,y_train)

pred = lr.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

cm =  confusion_matrix(y_test,pred)
sns.heatmap(cm,annot = True,cmap='viridis',cbar = False)

